# refer ldbc_finbench_transaction_impls/neo4j/conf/neo4j.conf

# === Memory Settings ===
# Machine has 256GB RAM; allocate 16GB to Heap, rest to Page Cache
server.memory.heap.initial_size=16g
server.memory.heap.max_size=16g
server.memory.pagecache.size=160g

# === Transaction & Logging ===
dbms.tx_log.rotation.retention_policy=1 files
dbms.tx_state.memory_allocation=ON_HEAP

# === Network & Connectors ===
server.bolt.thread_pool_min_size=50
server.bolt.thread_pool_max_size=400
server.default_listen_address=0.0.0.0

# === Plugins & Security ===
server.directories.plugins=/plugins
server.directories.logs=/logs
dbms.security.procedures.unrestricted=apoc.*
dbms.security.auth_enabled=false
